spring:
  application:
    name: account-service
  config:
    import: "configserver:"
  cloud:
    config:
      uri: http://localhost:8888
#server:
#  port: 8081
#  servlet:
#    context-path: /api/v1/accounts
#
#spring:
#  datasource:
#    url: jdbc:h2:mem:accountdb
#    driverClassName: org.h2.Driver
#    username: sa
#    password: password
#
#  h2:
#    console:
#      enabled: true
#      path: /h2-console
#
#  jpa:
#    hibernate:
#      ddl-auto: update
#    properties:
#      hibernate:
#        dialect: org.hibernate.dialect.H2Dialect
