spring:
  application:
    name: customer-service
  datasource:
    url: jdbc:h2:mem:customerdb
    driverClassName: org.h2.Driver
    username: sa
    password: password
  h2:
    console.enabled: true
  config:
    import: "optional:configserver:"
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
