server:
  port: 8080

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: account-service
          uri: lb://account-service
          predicates:
            - Path=/accounts/**
        - id: customer-service
          uri: lb://customer-service
          predicates:
            - Path=/customers/**

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
