#server:
#  port: 8080

spring:
  application:
    name: api-gateway
  config:
    import: "configserver:"
  cloud:
    config:
      uri: http://localhost:8888
#    gateway:
#      discovery:
#        locator:
#          enabled: true
#          lower-case-service-id: true
#      routes:
#        - id: customer-service
#          uri: lb://CUSTOMER-SERVICE
#          predicates:
#            - Path=/api/customers/**
#        - id: product-service
#          uri: lb://PRODUCT-SERVICE
#          predicates:
#            - Path=/api/products/**

#eureka:
#  client:
#    service-url:
#      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
#    fetch-registry: true
#    register-with-eureka: true

#management:
#  endpoints:
#    web:
#      exposure:
#        include: "*"include